# Generated by Django 3.0 on 2021-09-06 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.TextField(blank=True, null=True)),
                ('asset_description', models.TextField(blank=True, null=True)),
                ('asset_type', models.TextField(blank=True, null=True)),
                ('amount', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('transaction_date', models.DateField()),
                ('senator', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'StockTable',
                'managed': False,
            },
        ),
    ]
